### ISSUE TITLE
seflie upload시 CSRF 토큰 없어서 

### ISSUE THREAD

**Issue by aszxvcb** [comtimes/smile#18]
## 증상
- URL 없이 바로 업로드 기능 구현 이후 부터 셀피 업로드시 다음과 같은 에러가 발생합니다.

## Screenshot
![image](https://user-images.githubusercontent.com/40683310/83103952-b9ebf580-a0f2-11ea-8352-63742f7017ce.png)

**Comment by aszxvcb** [comment]
#18 Fix home2.html to upload selfie image.	aacb56f	SangHyeon <aszxvcb@gmail.com>	2020. 5. 28. 오후 3:03 커밋으로  이슈 해결

**Comment by zwonlala** [comment]
굳 내가 실수로 아래 바꾸는거 깜빡했는데 잘 고쳤넹
